<a href="https://colab.research.google.com/github/sum78435-lang/pythontibame/blob/main/webscrap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import urllib.request as req
import os
import json
import pandas as pd

serials = ["35241","35242","35243"]
dn = "baha/芙莉蓮"
def get_danmu(sn,dn,chapter=-1):
  if not os.path.exists(dn):
    os.makedirs(dn)
  url = f"https://api.gamer.com.tw/anime/v1/danmu.php?videoSn={sn}&geo=TW%2CHK"
  print("下載",url)

  f = req.urlopen(url)
  content = f.read()
  content = json.loads(content)
  danmus = content["data"]["danmu"]

  df = pd.DataFrame(danmus)
  df["ch"] = chapter
  df.to_csv(f"{dn}/{sn}.csv",encoding="utf-8")
  return df

get_danmu("35421","baha/芙莉蓮",30)


# for d in danmus:
#   print(d["userid"],d["text"])

下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=35421&geo=TW%2CHK

,text,color,size,position,time,sn,userid,ch
0,簽簽ukyo四刷！！,#FFFFFF,1,0,0,46978783,mishia0404,30
1,2024最後一天看到這集，真是感動,#FFFFFF,1,0,1,43290413,ss717678,30
2,簽！！！,#A7FE39,2,0,6,35944748,Cat971110,30
3,2023/10/20簽,#FFFFFF,1,0,6,35948122,sunny990803,30
4,簽🥖,#FF9496,1,0,8,49266942,alice1025102,30
...,...,...,...,...,...,...,...,...
928,太神辣！,#FFFFFF,1,0,14337,35934309,b730091,30
929,自己google啦,#FF9496,2,2,14340,36963108,z55423674,30
930,該不會是兩人份3D拼圖混在一起了,#FFFFFF,1,0,14345,35988966,areong,30
931,無水硫酸銅(白色) 碰水>藍色,#FFFFFF,1,0,14345,36229553,andyas123456,30
932,安安,#FFFFFF,1,0,14400,35933142,petet520,30

In [ ]:
f = open("test.csv","w",encoding="utf-8")
f.write("姓名,身高\n")
f.write("Andy,174\n")
f.write('"Bob,Mr.Chou",180')
f.close()

In [11]:
import os
import urllib.request as req
import bs4 as bs
# url ="https://ani.gamer.com.tw/animeVideo.php?sn=35241"
# url = "https://github.com/Elwing-Chou/tibame20260427/raw/refs/heads/main/%E8%8A%99%E8%8E%89%E8%93%AE.html"
url = "https://github.com/sum78435-lang/pythontibame/raw/refs/heads/main/%E8%8A%99%E8%8E%89%E8%93%AE.html"

h = {
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36"
}

r = req.Request(url,headers=h)
resp = req.urlopen(r)
content = resp.read()
html = bs.BeautifulSoup(content)
for a in html.find_all("a"):
  a_href = a["href"]
  a_text = a.get_text()
  if a_href.startswith("?sn"):
    print(a_text,a_href)
    sn = a_href.split("=")[-1]
    get_danmu(sn,dn,a_text)

1 ?sn=35241
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=35241&geo=TW%2CHK
2 ?sn=35242
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=35242&geo=TW%2CHK
3 ?sn=35243
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=35243&geo=TW%2CHK
4 ?sn=35244
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=35244&geo=TW%2CHK
5 ?sn=35445
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=35445&geo=TW%2CHK
6 ?sn=35446
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=35446&geo=TW%2CHK
7 ?sn=35447
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=35447&geo=TW%2CHK
8 ?sn=35660
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=35660&geo=TW%2CHK
9 ?sn=35781
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=35781&geo=TW%2CHK
10 ?sn=35845
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=35845&geo=TW%2CHK
11 ?sn=36046
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=36046&geo=TW%2CHK
12 ?sn=36128
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=36128&geo=TW%2CHK
13 ?sn=36196
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=36196&geo=TW%2CHK
14 ?sn=36260
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=36260&geo=TW%2CHK
15 ?sn=36371
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=36371&geo=TW%2CHK
16 ?sn=36553
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=36553&geo=TW%2CHK
17 ?sn=36554
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=36554&geo=TW%2CHK
18 ?sn=36861
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=36861&geo=TW%2CHK
19 ?sn=36862
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=36862&geo=TW%2CHK
20 ?sn=36991
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=36991&geo=TW%2CHK
21 ?sn=37034
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=37034&geo=TW%2CHK
22 ?sn=37100
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=37100&geo=TW%2CHK
23 ?sn=37237
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=37237&geo=TW%2CHK
24 ?sn=37362
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=37362&geo=TW%2CHK
25 ?sn=37407
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=37407&geo=TW%2CHK
26 ?sn=37408
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=37408&geo=TW%2CHK
27 ?sn=37628
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=37628&geo=TW%2CHK
28 ?sn=37668
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=37668&geo=TW%2CHK
1 ?sn=39208
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39208&geo=TW%2CHK
2 ?sn=39209
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39209&geo=TW%2CHK
3 ?sn=39210
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39210&geo=TW%2CHK
4 ?sn=39211
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39211&geo=TW%2CHK
5 ?sn=39212
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39212&geo=TW%2CHK
6 ?sn=39213
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39213&geo=TW%2CHK
7 ?sn=39214
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39214&geo=TW%2CHK
8 ?sn=39215
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39215&geo=TW%2CHK
9 ?sn=39216
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39216&geo=TW%2CHK
10 ?sn=39217
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39217&geo=TW%2CHK
11 ?sn=39218
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39218&geo=TW%2CHK
12 ?sn=39219
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39219&geo=TW%2CHK
13 ?sn=39220
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39220&geo=TW%2CHK
14 ?sn=39221
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39221&geo=TW%2CHK
15 ?sn=39222
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39222&geo=TW%2CHK
16 ?sn=39223
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39223&geo=TW%2CHK
17 ?sn=39224
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39224&geo=TW%2CHK
18 ?sn=39225
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39225&geo=TW%2CHK
19 ?sn=39226
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39226&geo=TW%2CHK
20 ?sn=39227
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39227&geo=TW%2CHK
21 ?sn=39228
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39228&geo=TW%2CHK
22 ?sn=39229
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39229&geo=TW%2CHK
23 ?sn=39230
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39230&geo=TW%2CHK
24 ?sn=39231
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39231&geo=TW%2CHK
25 ?sn=39232
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39232&geo=TW%2CHK
26 ?sn=39233
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39233&geo=TW%2CHK
27 ?sn=39234
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39234&geo=TW%2CHK
28 ?sn=39235
下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39235&geo=TW%2CHK

In [9]:
df = get_danmu("35421","baha/芙莉蓮",30)
df["text"]
cols = ["text","userid"]
df[cols]
df["new"] = 20
df

下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=35421&geo=TW%2CHK

,text,color,size,position,time,sn,userid,new
0,簽簽ukyo四刷！！,#FFFFFF,1,0,0,46978783,mishia0404,20
1,2024最後一天看到這集，真是感動,#FFFFFF,1,0,1,43290413,ss717678,20
2,簽！！！,#A7FE39,2,0,6,35944748,Cat971110,20
3,2023/10/20簽,#FFFFFF,1,0,6,35948122,sunny990803,20
4,簽🥖,#FF9496,1,0,8,49266942,alice1025102,20
...,...,...,...,...,...,...,...,...
928,太神辣！,#FFFFFF,1,0,14337,35934309,b730091,20
929,自己google啦,#FF9496,2,2,14340,36963108,z55423674,20
930,該不會是兩人份3D拼圖混在一起了,#FFFFFF,1,0,14345,35988966,areong,20
931,無水硫酸銅(白色) 碰水>藍色,#FFFFFF,1,0,14345,36229553,andyas123456,20
932,安安,#FFFFFF,1,0,14400,35933142,petet520,20

In [9]:
df = get_danmu("35421","baha/芙麗蓮",30)
test_df = df.head(3)
test_df

下載 https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=35421&geo=TW%2CHK

                text    color  size  position  time        sn      userid  ch
0         簽簽ukyo四刷！！  #FFFFFF     1         0     0  46978783  mishia0404  30
1  2024最後一天看到這集，真是感動  #FFFFFF     1         0     1  43290413    ss717678  30
2               簽！！！  #A7FE39     2         0     6  35944748   Cat971110  30

In [12]:
import glob
import pandas as pd
import os

dn = "baha/processed"
if not os.path.exists(dn):
  os.makedirs(dn)

total=[]

for fn in glob.glob("baha/*/*.csv"):
  df = pd.read_csv(fn,encoding="utf-8",index_col=0)
  total.append(df)
df = pd.concat(total)
df = df.sort_values(by="ch")
df = df.reset_index(drop=True)

# df["userid"].value_counts()
uids = df["userid"].unique()
for u in uids:
  fil = df["userid"] == u
  fp = f"{dn}/{u}.csv"
  df[fil].to_csv(fp,encoding="utf-8")